services:
  - type: web
    name: scd-colicoderviese-super-app
    runtime: node
    plan: free
    buildCommand: "npm run check"
    startCommand: "npm start"
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SCD_APPS_SCRIPT_URL
        value: https://script.google.com/macros/s/AKfycbwYQ_3yLYsp-6jX3FIgufBjpmaZb9uO1AklF9hdG-CuLII9J4ITUX1EA-EKuWXBMEc/exec