(()=>{
'use strict';
const NAV=[
  {id:'home',icon:'home',label:'Home'},
  {id:'calendario',icon:'calendar',label:'Calendario'},
  {id:'atleta',icon:'user',label:'Atleta'},
  {id:'famiglia',icon:'family',label:'Famiglia'},
  {id:'staff',icon:'staff',label:'Staff'},
  {id:'comunicazioni',icon:'news',label:'News'}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={screen:'home',events:[],news:[],partners:[],weekShift:0,day:'',type:'ALL',newsType:'ALL',source:'UNVERIFIED',fetched:false};
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=(v)=>String(v??'').trim();
const normType=(v)=>{const s=text(v).toUpperCase();if(/^(MATCH|GAME|GARA|PARTITA)$|CHAMPIONSHIP/.test(s))return'MATCH';if(/^(TRAINING|PRACTICE|ALLENAMENTO)$/.test(s))return'TRAINING';return'EVENT';};
const privateTypes=/SAFEGUARD|MEDIC|HEALTH|CERTIFIC|FAMILY|FAMIGL|PRIVATE|RISERVAT|PAYMENT|PAGAMENT|DOCUMENT|CONVOCA|MINOR|FINANC|PERSONAL|IDENTIT|DOSSIER/i;
function isPublic(row){if(!row||typeof row!=='object')return false;const visibility=text(row.visibility||row.VISIBILITY).toUpperCase();if(!['PUBLIC','PUBBLICO'].includes(visibility))return false;return ![row.type,row.kind,row.eventType,row.category,row.title,row.name].some(x=>privateTypes.test(text(x)));}
function eventOf(row){if(!isPublic(row))return null;const date=text(row.date||row.startDate||row.eventDate||row.start).slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(new Date(date+'T12:00:00Z').getTime()))return null;return{
  id:text(row.id||row.eventId||row.EVENT_ID||date+'-'+row.title),date,
  title:text(row.title||row.eventTitle||row.name||'Attivita SCD'),
  team:text(row.team||row.teamName||row.categoryName),opponent:text(row.opponent||row.opponentName),
  location:text(row.location||row.venue||row.place),time:text(row.time||row.startTime).slice(0,5),
  type:normType(row.type||row.kind||row.eventType),source:text(row.source||'FONTE_SCD')
};}
function newsOf(row){if(!row||typeof row!=='object')return null;const title=text(row.title||row.headline);if(!title||/NESSUNA NOTIZIA AUTOMATICA SENZA DATI VERIFICATI|WAITING_FOR_FACTS/i.test(title))return null;const link=text(row.url||row.link);if(link&&!/^https:\/\//i.test(link))return null;return{
 title,date:text(row.date||row.publishedAt||row.generatedAt),summary:text(row.summary||row.dek||row.description||''),url:link,source:text(row.source||'SCD'),
 kind:normType(row.type||row.category)==='EVENT'&&/EVENT|TORNEO|INIZIATIV/i.test(text(row.type||row.category))?'EVENT':'NEWS'
};}
function getRomeDay(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()).reduce((out,item)=>(out[item.type]=item.value,out),{});return p.year+'-'+p.month+'-'+p.day;}
function getWeekStart(shift=0){const today=getRomeDay();const d=new Date(today+'T12:00:00Z');const dow=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-dow+shift*7);return d;}
function dayKey(d){return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`;}
function formatDate(d,options={day:'numeric',month:'short'}){return new Intl.DateTimeFormat('it-IT',{timeZone:'UTC',...options}).format(d);}
function dateParts(date){const d=new Date(date+'T12:00:00Z');return{day:formatDate(d,{day:'2-digit'}),short:formatDate(d,{weekday:'short'}).replace('.','').toUpperCase(),human:formatDate(d,{weekday:'short',day:'numeric',month:'short'}),full:formatDate(d,{weekday:'long',day:'numeric',month:'long'})};}
function svg(id){return `<svg aria-hidden="true"><use href="#i-${id}"></use></svg>`;}
function renderNav(){for(const entry of NAV){const button=document.createElement('button');button.type='button';button.dataset.screen=entry.id;button.innerHTML=svg(entry.icon)+`<span>${entry.label}</span>`;button.setAttribute('aria-label',entry.label);$('#bottomNav').append(button);const desktop=button.cloneNode(true);$('#desktopNav').append(desktop);}}
function navigate(screen){if(!NAV.some(item=>item.id===screen))return;state.screen=screen;$$('main > .screen').forEach(element=>{const active=element.dataset.page===screen;element.classList.toggle('active',active);element.hidden=!active;});$$('#desktopNav [data-screen],#bottomNav [data-screen]').forEach(button=>{const active=button.dataset.screen===screen;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');});$('#main').scrollTop=0;try{history.replaceState(null,'','#'+screen)}catch{}document.title=(NAV.find(item=>item.id===screen)?.label||'Club')+' | SCD Colicoderviese';}
function eventKindLabel(kind){return kind==='MATCH'?'GARA':kind==='TRAINING'?'ALLENAMENTO':'EVENTO';}
function renderEvent(event){const d=dateParts(event.date);return`<article class="agenda-entry ${event.type==='MATCH'?'match':event.type==='TRAINING'?'training':'event'}"><span class="agenda-bar"></span><div class="agenda-date"><span>${escapeHTML(d.short)}</span><strong>${escapeHTML(d.day)}</strong></div><div class="agenda-text"><strong>${escapeHTML(event.title)}</strong><small>${escapeHTML([event.team,event.location].filter(Boolean).join(' / ')||'Luogo in aggiornamento')}</small></div><div class="agenda-meta"><span>${escapeHTML(event.time||'N/D')}</span><span>${eventKindLabel(event.type)}</span></div></article>`;}
function renderWeek(){const monday=getWeekStart(state.weekShift);const sunday=new Date(monday);sunday.setUTCDate(sunday.getUTCDate()+6);$('#weekLabel').textContent=`${formatDate(monday)} - ${formatDate(sunday,{day:'numeric',month:'short',year:'numeric'})}`;const today=getRomeDay();let days='';for(let i=0;i<7;i++){const day=new Date(monday);day.setUTCDate(day.getUTCDate()+i);const key=dayKey(day);days+=`<button type="button" data-day="${key}" class="${state.day===key||(!state.day&&key===today)?'selected':''}" aria-label="${escapeHTML(dateParts(key).full)}">${escapeHTML(dateParts(key).short)}<strong>${day.getUTCDate()}</strong></button>`;}
$('#weekDays').innerHTML=days;const from=dayKey(monday),to=dayKey(sunday);const rows=state.events.filter(event=>event.date>=from&&event.date<=to&&(!state.day||state.day===event.date)&&(state.type==='ALL'||state.type===event.type));$('#calendarEvents').innerHTML=rows.length?rows.map(renderEvent).join(''):'<p class="no-data">Nessuna attivit\u00e0 pubblica verificata per questo periodo e filtro.</p>';}
function renderMatch(){const next=state.events.find(event=>event.type==='MATCH'&&event.date>=getRomeDay());const chip=$('#matchSourceChip');if(!next){chip.textContent='IN AGGIORNAMENTO';chip.className='chip-verified';$('#nextMatchContent').innerHTML='<div class="no-data">Nessuna prossima gara verificata disponibile. Verr\u00e0 pubblicata quando la fonte ufficiale sar\u00e0 aggiornata.</div>';return;}const synthetic=/STAGING|TEST|SYNTHETIC/i.test(next.source);chip.textContent=synthetic?'DATI DI PROVA':'FONTE PUBBLICA';chip.className='chip-verified '+(synthetic?'synthetic':'real');$('#nextMatchContent').innerHTML=`<div class="match-teams"><div class="match-side"><img alt="SCD" src="${document.querySelector('.brand-trigger img')?.getAttribute('src')||'assets/logo-scd.png'}"><strong>SCD COLICODERVIESE</strong><small>${escapeHTML(next.team)}</small></div><div class="match-vs">VS<small>${escapeHTML(next.time||'N/D')}</small></div><div class="match-side"><div class="opponent-crest" aria-hidden="true">${svg('ball')}</div><strong>${escapeHTML(next.opponent||'Avversario da confermare')}</strong><small>Ospiti</small></div></div><div class="match-date"><span>${escapeHTML(dateParts(next.date).human)}</span><span>${escapeHTML(next.location||'Campo da verificare')}</span></div>`;}
function renderNewsItem(news){const link=news.url?`<a href="${escapeHTML(news.url)}" rel="noopener noreferrer" target="_blank">${escapeHTML(news.title)}</a>`:escapeHTML(news.title);return `<article class="news-story"><div class="news-symbol">${svg(news.kind==='EVENT'?'calendar':'news')}</div><div><h3>${link}</h3><small>${escapeHTML([news.date?.slice(0,10),news.source].filter(Boolean).join(' / '))}</small>${news.summary?`<p>${escapeHTML(news.summary.slice(0,150))}</p>`:''}</div></article>`;}
function renderNews(){const filtered=state.news.filter(n=>state.newsType==='ALL'||n.kind===state.newsType);$('#communicationsList').innerHTML=filtered.length?filtered.map(renderNewsItem).join(''):'<p class="no-data">Nessuna notizia ufficiale verificata disponibile con questo filtro.</p>';$('#homeNews').innerHTML=state.news.length?state.news.slice(0,2).map(renderNewsItem).join(''):'<p class="no-data">Notizie ufficiali in aggiornamento.</p>';}
function renderPartners(){const area=$('#sponsorList');if(!state.partners.length){area.innerHTML='<p class="no-data">Partner in aggiornamento. Consulta le iniziative ufficiali SCD.</p>';return;}area.innerHTML=state.partners.slice(0,4).map(n=>`<span class="sponsor-chip">${escapeHTML(n)}</span>`).join('');}
function renderSections(){renderMatch();renderWeek();renderNews();renderPartners();const current=state.events.filter(e=>e.date>=getRomeDay());$('#familyEvents').innerHTML=current.length?current.slice(0,2).map(renderEvent).join(''):'<p class="no-data">Attivit\u00e0 pubbliche in aggiornamento.</p>';$('#staffEvents').innerHTML=current.length?current.slice(0,3).map(renderEvent).join(''):'<p class="no-data">Attivit\u00e0 pubbliche in aggiornamento.</p>';}
async function loadPublic(){let status='DATI IN AGGIORNAMENTO / NESSUN DATO INVENTATO';try{const response=await fetch('/api/newsroom',{headers:{accept:'application/json'},cache:'no-store',signal:AbortSignal.timeout(7000)});if(!response.ok)throw Error('HTTP '+response.status);const value=await response.json();const data=value.data||value;let input=Array.isArray(data.calendar?.rows)?data.calendar.rows:Array.isArray(data.calendar)?data.calendar:Array.isArray(data.events)?data.events:[];const rawNews=Array.isArray(data.news?.items)?data.news.items:Array.isArray(data.news)?data.news:Array.isArray(data.cards)?data.cards:[];const rawPartners=Array.isArray(data.partners)?data.partners:[];state.events=[...new Map(input.map(eventOf).filter(Boolean).map(x=>[x.id,x])).values()].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));state.news=rawNews.map(newsOf).filter(Boolean).slice(0,30);state.partners=rawPartners.filter(p=>p&&typeof p==='object'&&(p.name||p.title)&&!p.private&&!p.restricted).map(p=>text(p.name||p.title)).slice(0,8);state.source=state.events.some(e=>/STAGING|TEST|SYNTHETIC/i.test(e.source))?'STAGING_SYNTHETIC':'PUBLIC_FEED';status=(state.source==='STAGING_SYNTHETIC'?'COLLAUDO / DATI SINTETICI':'FONTE PUBBLICA / SOLO INFORMAZIONI VERIFICATE')+` / ${state.events.length} attivita`;}
catch(error){state.source='UNAVAILABLE';state.events=[];state.news=[];state.partners=[];status='DATI PUBBLICI MOMENTANEAMENTE NON DISPONIBILI';}
state.fetched=true;$('#sourceMessage').textContent=status;renderSections();}
function showPrivate(module){$('#privateTitle').textContent='Accesso autorizzato / '+module;$('#privateDialog').hidden=false;$('#privateDialog .close-dialog').focus();}
function showSky(){if(!$('#skyDialog'))return;$('#skyDialog').hidden=false;$('#skyQuestion').focus();}
function closeDialogs(){$$('#privateDialog,#skyDialog').forEach(d=>d.hidden=true);}
async function askSky(){const question=$('#skyQuestion').value.trim(),result=$('#skyResult');if(!question)return;result.textContent='Sto controllando le informazioni pubbliche...';$('#skyAsk').disabled=true;try{const response=await fetch('/api/sky/ask',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question,app:'ONE'})});if(!response.ok)throw Error('SKY_NOT_AVAILABLE');const body=await response.json();result.textContent=body.data?.answer||'Informazione in aggiornamento.';}catch{result.textContent='Sky non e\u00a0disponibile in questa anteprima. Puoi contattare sportclubcolico@gmail.com.';}finally{$('#skyAsk').disabled=false;}}
function changeFilter(kind){state.type=kind;state.day='';$$('[data-event-type]').forEach(b=>b.classList.toggle('active',b.dataset.eventType===kind));renderWeek();}
function changeNewsFilter(kind){state.newsType=kind;$$('[data-news-filter]').forEach(b=>b.classList.toggle('active',b.dataset.newsFilter===kind));renderNews();}
let started=false;
function init(){if(started)return;started=true;renderNav();document.addEventListener('click',event=>{const control=event.target.closest('button,a');if(!control)return;const route=control.dataset.screen;if(route){event.preventDefault();navigate(route);if(control.dataset.filter)changeFilter(control.dataset.filter);if(control.dataset.newsFilter)changeNewsFilter(control.dataset.newsFilter);return;}if(control.dataset.private){showPrivate(control.dataset.private);return;}if(control.dataset.eventType){changeFilter(control.dataset.eventType);return;}if(control.dataset.newsFilter){changeNewsFilter(control.dataset.newsFilter);return;}if(control.dataset.day){state.day=control.dataset.day;renderWeek();return;}if(control.dataset.closeDialog!==undefined){closeDialogs();return;}if(control.dataset.skySuggestion){$('#skyQuestion').value=control.dataset.skySuggestion;askSky();return;}});
$('#weekPrev').addEventListener('click',()=>{state.weekShift--;state.day='';renderWeek()});$('#weekNext').addEventListener('click',()=>{state.weekShift++;state.day='';renderWeek()});$('#skyLaunch').addEventListener('click',showSky);$('#skyAsk').addEventListener('click',askSky);$$('.dialog-backdrop').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog)closeDialogs()}));document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDialogs()});const initial=location.hash.replace('#','');navigate(NAV.some(x=>x.id===initial)?initial:'home');renderSections();loadPublic();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.SCDPhotoApp={navigate,isPublic,eventOf,getSource:()=>state.source};
})();