const DATA={
sponsors:[
{name:"Noratech Srl",sector:"Tecnologia / corporate",status:"DOCUMENTATO",value:"€400 + IVA",asset:"Social + Centro Sportivo",period:"17/07/2026 - 30/12/2026",class:"ATTIVO - DA DIFENDERE / SVILUPPARE",next:"Verificare posizione amministrativa; Sponsor Report 2026; proposta upgrade 2027",tags:["Social","Centro Sportivo"],history:"Rapporto documentato; ipotesi precedenti U16/LED/mascotte non equivalgono al contratto finale."},
{name:"Coperture Rasero Srl",sector:"Edilizia / visibilità impianto",status:"DOCUMENTATO",value:"€500 + IVA",asset:"Striscione bordo campo + sito",period:"15/04/2026 - 15/04/2027",class:"ATTIVO - DA RINNOVARE",next:"Mappare posizione/dimensioni striscione e preparare rinnovo",tags:["Cartellonistica","Digital"],history:"Contratto documentato con asset fisico e digitale."},
{name:"Officine Pedroncelli Srl",sector:"Mobility / officina",status:"DOCUMENTATO",value:"€500 + IVA / anno",asset:"Logo sui vetri laterali del pulmino",period:"Rapporto pluriennale",class:"ATTIVO - DA SVILUPPARE",next:"Verificare scadenza, pagamento e foto attuale mezzo",tags:["Mobility","Pulmino"],history:"Rapporto avviato nel 2024; annualità 2026 verificata."},
{name:"DECAR Srl",sector:"Automotive",status:"ECONOMICAMENTE DOCUMENTATO",value:"€1.500 + IVA",asset:"Asset 2026 da ricostruire",period:"2026",class:"AUDIT PRIMA DEL RINNOVO",next:"Recuperare contratto/accordo 2026 e identificare asset",tags:["Automotive","Audit"],history:"Riferimenti storici a divise, ma non attribuibili automaticamente al 2026."},
{name:"SACO Multiservizi",sector:"Servizi / partnership territoriale",status:"ECONOMICAMENTE DOCUMENTATO",value:"Rapporto ibrido",asset:"Sponsor + fornitura/protezioni",period:"2026",class:"DA NORMALIZZARE",next:"Separare sponsorship, fornitura, barter e cost saving",tags:["Servizi","Barter"],history:"Non conteggiare automaticamente come puro cash sponsor."},
{name:"Bianchi Bazzi Angelo Srl",sector:"Corporate / territorio",status:"ECONOMICAMENTE DOCUMENTATO",value:"€1.500 + IVA",asset:"Asset 2026 da ricostruire",period:"2026",class:"DA RICOSTRUIRE",next:"Recuperare accordo, durata e materiali esposti",tags:["Corporate","Audit"],history:"Rapporto storico rilevante; asset 2026 non certo."},
{name:"Saglio Sport / LEGEA",sector:"Sportswear / partner tecnico",status:"PARTNER TECNICO DA COMPLETARE",value:"DA VERIFICARE",asset:"Fornitura tecnica, kit e abbigliamento",period:"2026/27 da verificare",class:"AUDIT OBBLIGATORIO",next:"Ricostruire accordo, durata, valore, categorie ed esclusività",tags:["Partner tecnico","Kit"],history:"Non trattare come sponsorship cash finché non ricostruiamo controprestazioni."}
],
responses:[
{date:"22/09",name:"Iperal",area:"Family & Community Partner",outcome:"In valutazione interna",next:"Follow-up leggero",priority:"ALTA"},
{date:"21/09",name:"Caffè Teti",area:"Coffee Partner / Club House",outcome:"Positivo",next:"Sopralluogo + proposta finale",priority:"URGENTE"},
{date:"21/09",name:"VIP Immagine",area:"Cartellonistica / sponsor board",outcome:"Positivo - chiede contatto",next:"Telefonare + mappa spazi/foto",priority:"URGENTE"},
{date:"22/09",name:"McDonald's territoriale",area:"Convenzione tesserati",outcome:"Proposta concreta 10%",next:"Formalizzare convenzione",priority:"ALTA"},
{date:"22/09",name:"La Roncaiola",area:"Lavanderia tecnica",outcome:"Interessata",next:"Definire volumi/frequenza",priority:"ALTA"},
{date:"22/09",name:"Bonazzi Grafica",area:"Grafica / stampa / packaging",outcome:"Interessata",next:"Fabbisogno annuo + barter",priority:"ALTA"},
{date:"26/09",name:"Lario Spurghi",area:"Servizi eventi",outcome:"Positivo",next:"Chiedere listino eventi",priority:"URGENTE"},
{date:"21/09",name:"Therabody",area:"Recovery Partner",outcome:"Instradato B2B",next:"Compilare form partnership",priority:"ALTA"},
{date:"23/09",name:"Galbusera",area:"Food & Event Partner",outcome:"Inoltrata internamente",next:"Follow-up marketing",priority:"MEDIA"},
{date:"25/09",name:"Lauretana",area:"Official Water Partner",outcome:"Rifiutata per budget",next:"Riaprire estate 2027",priority:"CHIUSA"},
{date:"23/09",name:"Acqua Sant'Anna",area:"Official Water Partner",outcome:"Rifiutata",next:"Riaprire fine 2027",priority:"CHIUSA"},
{date:"28/09",name:"Foresteria Villa Simona",area:"Hospitality",outcome:"Non adatta alla continuità",next:"Mantenere contatto occasionale",priority:"BASSA"}
],
assets:[
["Family & Community Partner","Community","GDO / banca / assicurazione","€5.000","Disponibile"],
["Official Water Partner","Fornitura / branding","Acque minerali / beverage","Da definire","In proposta"],
["Official Coffee Partner","Club House","Torrefazioni / beverage","Da definire","In proposta"],
["Official Hospitality Partner","Hospitality","Beverage / hospitality","Da definire","In proposta"],
["Fondo Solidale / Sport & Futuro","Sociale","Banche / fondazioni / imprese","€2.500","Attivo"],
["Servizio Navetta","Servizio famiglie","Automotive / energia / mobilità","Da definire","Attivo"],
["Torneo Title Sponsor","Evento","Banche / GDO / grandi imprese","€7.000","Disponibile"],
["Centro Sportivo - Area Club House","Struttura","Banca / horeca / arredamento","Da definire","Disponibile"],
["Area giochi / fitness outdoor","Struttura","Outdoor / wellness / healthcare","Da definire","In sviluppo"],
["LED bordo campo","Media","PMI / sponsor multipli","Da definire","Disponibile"],
["Divise settore giovanile","Kit tecnico","Aziende territoriali","€1.500","Parzialmente disponibile"],
["Sport Tourism Network","Turismo","Hotel / ristorazione / hospitality","Da definire","In sviluppo"],
["Performance & Recovery Center","Salute / Performance","Medicale / wellness / recovery","Da definire","Da studiare"],
["Media Center & Content Lab","Media / Digitale","Media / telecom / tecnologia","Da definire","Da studiare"],
["SCD Partner Club","B2B / Networking","Partner strategici","Da definire","Da studiare"],
["Youth Development Partner","Settore giovanile","Banche / industria / tech","Da definire","Da studiare"],
["Goalkeeper Academy Partner","Settore giovanile","Sport equipment / performance","Da definire","Da studiare"],
["Centro Sportivo Montecchi Main Partner","Struttura / Naming","Banca / industria / infrastrutture","Da definire","Da studiare"]
],
led:[
["DEGO ARREDAMENTI","Arredamento / design","IN REVISIONE"],["ATV VALVE","Industria / valvole","IN REVISIONE"],["IPERAL","GDO / retail","IN REVISIONE"],["LEGEA","Sportswear / partner tecnico","IN REVISIONE"],["NBC ELETTRONICA","Elettronica / tecnologia","IN REVISIONE"],["SAGLIO SPORT","Sportswear / partner tecnico","IN REVISIONE"],["HDI MAGLIA","Assicurazioni","ATTESA APPROVAZIONE"],["DELLOCA","Energia / carburanti","ATTESA APPROVAZIONE"],["CARCANO","Industria / alluminio","ATTESA APPROVAZIONE"],["MDS IMPIANTI","Impiantistica","FONTI VERIFICATE"],["RIGAMONTI GEOM. GINO","Edilizia / infrastrutture","FONTI VERIFICATE"],["TARABINI PAOLO","Termoidraulica","FONTI VERIFICATE"],["TURBOJET SPURGHI","Servizi ambientali","FONTI VERIFICATE"],["GGLASS","Auto / cristalli","FONTI VERIFICATE"],["BIRRIFICIO LEGNONE","Food & Beverage","FONTI VERIFICATE"],["RIVARENO COLICO","Gelateria / retail","FONTI VERIFICATE"],["TRAFILERIE ALLUMINIO ALEXIA","Industria / alluminio","FONTI VERIFICATE"],["GAIO BAR RISTORANTE","Ristorazione / eventi","FONTI VERIFICATE"],["I VIAGGI DELLO SQUALO","Turismo / viaggi","FONTI VERIFICATE"]
],
tasks:[
["URGENTE","Caffè Teti","Sopralluogo e proposta finale"],["URGENTE","VIP Immagine","Telefonare e inviare mappa spazi/foto"],["URGENTE","Lario Spurghi","Chiedere listino eventi 1g/2g"],["ALTA","Therabody","Compilare form EU Partnership"],["ALTA","McDonald's","Formalizzare convenzione 10%"],["ALTA","La Roncaiola","Definire volumi, frequenza, luogo ritiro"],["ALTA","Iperal","Follow-up leggero"],["ALTA","Bonazzi Grafica","Inviare fabbisogno annuo + barter"],["MEDIA","Galbusera","Follow-up marketing"],["MOLTO ALTA","DECAR","Audit accordo e asset 2026"],["MOLTO ALTA","SACO","Separare sponsor, fornitura e barter"]
]
};
const initials=n=>n.split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase();
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
function openView(name){qsa(".view").forEach(v=>v.classList.remove("active"));qs("#view-"+name)?.classList.add("active");qsa(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===name));window.scrollTo({top:0,behavior:"smooth"});if(innerWidth<801)qs("#sidebar").classList.remove("open")}
qsa("[data-view]").forEach(b=>b.onclick=()=>openView(b.dataset.view));qsa("[data-open-view]").forEach(b=>b.onclick=()=>openView(b.dataset.openView));
qs("#mobileMenu").onclick=()=>qs("#sidebar").classList.toggle("open");
function sponsorCard(s){return `<article class="sponsor-card" data-name="${s.name.toLowerCase()}" onclick="showSponsor('${s.name.replace(/'/g,"\\'")}')"><div class="sponsor-head"><div class="logo-box">${initials(s.name)}</div><div><h3>${s.name}</h3><p>${s.sector}</p></div><span class="status">${s.status}</span></div><div class="sponsor-tags">${s.tags.map(t=>`<span>${t}</span>`).join("")}</div><div class="sponsor-data"><div><small>VALORE</small><b>${s.value}</b></div><div><small>PERIODO</small><b>${s.period}</b></div><div><small>ASSET</small><b>${s.asset}</b></div><div><small>STATO</small><b>${s.class}</b></div></div></article>`}
qs("#sponsorGrid").innerHTML=DATA.sponsors.map(sponsorCard).join("");
qs("#storiciGrid").innerHTML=DATA.sponsors.filter(s=>["Noratech Srl","Officine Pedroncelli Srl","Saglio Sport / LEGEA"].includes(s.name)).map(sponsorCard).join("");
qs("#convenzioniGrid").innerHTML=DATA.responses.map(r=>`<article class="pipeline-card"><div style="display:flex;justify-content:space-between;gap:8px"><h3>${r.name}</h3><span class="priority">${r.priority}</span></div><p>${r.area}</p><div class="row"><span>Esito</span><b>${r.outcome}</b></div><div class="row"><span>Prossima azione</span><b>${r.next}</b></div></article>`).join("");
qs("#assetGrid").innerHTML=DATA.assets.map(a=>`<article class="asset-card"><h3>${a[0]}</h3><p>${a[1]} · Target: ${a[2]}</p><footer><b>${a[3]}</b><span class="asset-state">${a[4]}</span></footer></article>`).join("");
qs("#ledBoard").innerHTML=DATA.led.map(x=>`<article class="led-row"><div class="led-logo">${initials(x[0])}</div><div><h3>${x[0]}</h3><p>${x[1]}</p></div><span class="led-state">${x[2]}</span></article>`).join("");
qs("#taskBoard").innerHTML=DATA.tasks.map(t=>`<article class="task"><span class="priority">${t[0]}</span><b>${t[1]}</b><small>${t[2]}</small><button class="secondary">Apri</button></article>`).join("");
qs("#todayList").innerHTML=DATA.tasks.slice(0,6).map((t,i)=>`<div class="today-item ${i<3?"urgent":""}"><b>${t[1]}</b><span>${t[2]}</span></div>`).join("");
qs("#recentTimeline").innerHTML=DATA.responses.slice(0,6).map(r=>`<div class="time-row"><time>${r.date}</time><div><b>${r.name}</b><span>${r.outcome}</span></div><span class="tag">${r.priority}</span></div>`).join("");
qs("#insights").innerHTML=[
["Contratti/asset da ricostruire","DECAR e Bianchi Bazzi hanno valore economico documentato ma asset 2026 ancora da identificare."],
["Rapporto ibrido da separare","SACO non deve essere contato automaticamente come puro cash sponsor: sponsorship, fornitura e barter vanno distinti."],
["Rinnovi da preparare","Coperture Rasero va impostato per rinnovo entro febbraio 2027; Noratech richiede report 2026 e proposta upgrade."],
["LED bloccati","3 sponsor sono in attesa approvazione; 6 in revisione; il resto richiede completamento fonti/materiali."]
].map(x=>`<div class="insight"><b>${x[0]}</b><p>${x[1]}</p></div>`).join("");
qs("#researchPipeline").innerHTML=DATA.responses.filter(r=>!r.priority.includes("CHIUSA")).slice(0,9).map(r=>`<div class="research-row"><div><b>${r.name}</b><small style="display:block;color:#718096">${r.area}</small></div><span>${r.outcome}</span><span>${r.priority}</span><span>${r.next}</span></div>`).join("");
qs("#radarList").innerHTML=["Banche & Finanza","Industria Alto Lago / Valtellina","Healthcare & Recovery","Technology & Telecom","Hospitality & Turismo","Food & Beverage","Mobility & Automotive"].map((x,i)=>`<div class="radar"><b>${x}</b><span>${i<3?"PRIORITÀ":"SVILUPPO"}</span></div>`).join("");
window.showSponsor=name=>{const s=DATA.sponsors.find(x=>x.name===name);if(!s)return;qs("#sponsorDetail").innerHTML=`<div class="detail-hero"><div class="logo-box">${initials(s.name)}</div><div><small>SPONSOR / PARTNER</small><h2>${s.name}</h2><p>${s.sector} · ${s.class}</p></div></div><div class="tabs">${["OVERVIEW","CONTRATTI ATTUALI","PROPOSTE / IPOTESI","SPONSORIZZAZIONI & ASSET","STORICO","CONTATTI","DOCUMENTI & CARTELLE","MATERIALI BRAND","LED","ECONOMICO DIREZIONE","TIMELINE"].map((t,i)=>`<button class="${i===0?"active":""}">${t}</button>`).join("")}</div><div class="detail-content"><div class="detail-box"><small>VALORE VERIFICATO</small><b>${s.value}</b></div><div class="detail-box"><small>PERIODO</small><b>${s.period}</b></div><div class="detail-box"><small>ASSET</small><b>${s.asset}</b></div><div class="detail-box"><small>PROSSIMA AZIONE</small><b>${s.next}</b></div></div><div style="margin-top:14px;background:#f7f9fb;padding:14px;border-radius:14px;font-size:10px;line-height:1.55"><b>Storico / nota</b><br>${s.history}</div><div class="folder-grid">${["Contratti","Proposte","Loghi","Foto","Video / LED","Email & Verbali","Fatture","Report"].map(f=>`<div class="folder">${f}<small style="display:block;color:#718096;margin-top:4px">Apri cartella</small></div>`).join("")}</div>`;qs("#sponsorModal").hidden=false};
qsa("[data-close-modal]").forEach(b=>b.onclick=()=>b.closest(".modal-wrap").hidden=true);
[qs("#newSponsorBtn"),qs("#newSponsorBtn2")].forEach(b=>{if(b)b.onclick=()=>qs("#newSponsorModal").hidden=false});
qs("#newSponsorForm").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),draft={name:f.get("name"),sector:f.get("sector"),contact:f.get("contact"),email:f.get("email"),season:f.get("season"),type:f.get("type"),notes:f.get("notes"),created:new Date().toISOString()};const arr=JSON.parse(localStorage.getItem("scd_sponsor_drafts")||"[]");arr.push(draft);localStorage.setItem("scd_sponsor_drafts",JSON.stringify(arr));alert("Bozza salvata localmente. Nessun dato è stato inviato fuori dal dispositivo.");qs("#newSponsorModal").hidden=true;e.target.reset()};
function allSearchItems(){return [...DATA.sponsors.map(s=>({title:s.name,meta:"Sponsor · "+s.sector,view:"attuali",action:()=>showSponsor(s.name)})),...DATA.responses.map(r=>({title:r.name,meta:"Pipeline · "+r.area,view:"convenzioni"})),...DATA.assets.map(a=>({title:a[0],meta:"Asset · "+a[1],view:"asset"})),...DATA.led.map(x=>({title:x[0],meta:"LED · "+x[2],view:"led"}))]}
const globalSearch=qs("#globalSearch"),searchResults=qs("#searchResults");globalSearch.oninput=()=>{const q=globalSearch.value.toLowerCase().trim();if(!q){searchResults.hidden=true;return}const found=allSearchItems().filter(x=>(x.title+" "+x.meta).toLowerCase().includes(q)).slice(0,12);searchResults.innerHTML=found.length?found.map((x,i)=>`<div class="search-result" data-i="${i}"><b>${x.title}</b><small>${x.meta}</small></div>`).join(""):`<div class="search-result"><b>Nessun risultato</b><small>Prova con sponsor, LED, asset o azienda.</small></div>`;searchResults.hidden=false;qsa(".search-result[data-i]").forEach(el=>el.onclick=()=>{const x=found[+el.dataset.i];openView(x.view);searchResults.hidden=true;globalSearch.value="";if(x.action)setTimeout(x.action,80)})};document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();globalSearch.focus()}});
qsa(".local-search").forEach(inp=>inp.oninput=()=>{const q=inp.value.toLowerCase();qs("#"+inp.dataset.target).querySelectorAll("[data-name]").forEach(c=>c.hidden=!c.dataset.name.includes(q))});
qs("#statusFilter").onchange=e=>qsa("#sponsorGrid .sponsor-card").forEach((c,i)=>c.hidden=e.target.value&&!DATA.sponsors[i].status.includes(e.target.value));
const assistant=qs("#assistant");qs("#assistantFab").onclick=()=>assistant.hidden=false;qs("#assistantClose").onclick=()=>assistant.hidden=true;
function botAnswer(q){const t=q.toLowerCase();if(t.includes("oggi")||t.includes("fare"))return "Priorità immediate: Caffè Teti, VIP Immagine e Lario Spurghi. Subito dopo: McDonald's, Therabody, Iperal e audit DECAR/SACO.";if(t.includes("led"))return "LED: HDI Maglia, Dell'Oca e Carcano sono in attesa approvazione. DEGO, ATV, Iperal, LEGEA, NBC e Saglio sono in revisione. Gli altri richiedono completamento fonti/materiali.";if(t.includes("asset")&&t.includes("liber"))return "Asset indicati come disponibili: Family & Community Partner, Torneo Title Sponsor, Centro Sportivo - Area Club House e LED bordo campo. Va comunque verificata ogni esclusiva prima di proporre.";if(t.includes("rinn"))return "Rinnovi prioritari: Coperture Rasero entro febbraio 2027. Noratech richiede report 2026 e proposta upgrade. Pedroncelli va verificata la scadenza finale.";const sponsor=DATA.sponsors.find(s=>t.includes(s.name.toLowerCase().split(" ")[0]));if(sponsor)return sponsor.name+": "+sponsor.class+". Prossima azione: "+sponsor.next+". Valore: "+sponsor.value+".";return "Posso aiutarti con sponsor, contratti, LED, rinnovi, asset, pipeline e prossime azioni. I suggerimenti derivano solo dai dati presenti in questa Web App."}
function addMsg(text,cls){const d=document.createElement("div");d.className=cls;d.textContent=text;qs("#assistantBody").appendChild(d);qs("#assistantBody").scrollTop=qs("#assistantBody").scrollHeight}
qs("#assistantForm").onsubmit=e=>{e.preventDefault();const q=qs("#assistantInput").value.trim();if(!q)return;addMsg(q,"user-msg");qs("#assistantInput").value="";setTimeout(()=>addMsg(botAnswer(q),"bot-msg"),150)};qsa(".quick-prompts button").forEach(b=>b.onclick=()=>{addMsg(b.textContent,"user-msg");setTimeout(()=>addMsg(botAnswer(b.textContent),"bot-msg"),100)});
