import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const host=process.env.SCD_BASE_URL||'http://127.0.0.1:4173';
fs.mkdirSync('test-output',{recursive:true});
const browser=await chromium.launch({headless:true});
let failed=false;
for (const [name,width,height] of [['mobile',390,844],['desktop',1440,900]]) {
 const page=await browser.newPage({viewport:{width,height},deviceScaleFactor:1,reducedMotion:'reduce'});
 const errors=[];
 page.on('pageerror',e=>errors.push(String(e)));
 const res=await page.goto(host+'/vision-2026',{waitUntil:'networkidle',timeout:25000});
 assert.equal(res.status(),200,'Expected route to serve HTTP 200');
 await page.getByRole('heading',{name:/Questa settimana/i}).waitFor();
 await page.locator('[data-testid="sky-original"]').waitFor();
 await page.evaluate(async()=>Promise.all([...document.images].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=resolve;img.onerror=resolve;}))));
 assert.ok(await page.locator('[data-testid="sky-original"]').evaluate(x=>x.naturalWidth>0),'Official isolated Sky must load');
 assert.ok(await page.locator('.scd-one-brand img').evaluate(x=>x.naturalWidth>0),'Official crest must load');
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);
 assert.ok(overflow<=2,`Horizontal overflow at ${width}px: ${overflow}px`);
 await page.screenshot({path:`test-output/scd-one-home-${name}-${width}x${height}.png`,fullPage:true});
 await page.locator('[data-testid="quick-allenamenti"]').click();
 await page.locator('[data-testid="activity-panel"]').getByText(/Allenamenti · In aggiornamento/).waitFor();
 await page.getByRole('button',{name:'Settimana successiva'}).first().click();
 assert.ok((await page.locator('[data-testid="week-label"]').innerText()).trim().length>5);
 const calendar=name==='mobile'?'mobile-nav-calendar':'nav-calendar';
 await page.locator(`[data-testid="${calendar}"]`).click();
 await page.getByRole('heading',{name:'Calendario Live'}).waitFor();
 await page.locator(`[data-testid="${name==='mobile'?'mobile-nav-home':'nav-home'}"]`).click();
 await page.getByRole('heading',{name:/Questa settimana/i}).waitFor();
 await page.locator('[data-testid="sky-open"]').click();
 await page.getByRole('dialog').getByText('Ciao! Sono Sky.').waitFor();
 await page.getByRole('button',{name:'Ho capito'}).click();
 assert.equal(await page.getByRole('dialog').count(),0,'Sky modal must close');
 assert.deepEqual(errors,[],'Browser runtime must be free of unhandled errors');
 console.log(`SCD ONE ${name}: HTTP200, original images, responsive no overflow, activity switch, week, calendar nav, Sky modal, screenshot PASS`);
 await page.close();
}
await browser.close();
if(failed)process.exitCode=1;
