/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllenamentiRouteImport } from './routes/allenamenti'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as EntraRouteImport } from './routes/entra'
import { Route as EventiRouteImport } from './routes/eventi'
import { Route as FornitoriRouteImport } from './routes/fornitori'
import { Route as SafeguardingRouteImport } from './routes/safeguarding'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SocietaRouteImport } from './routes/societa'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as AreeIndexRouteImport } from './routes/aree.index'
import { Route as AreeAreaRouteImport } from './routes/aree.$area'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllenamentiRoute = AllenamentiRouteImport.update({
  id: '/allenamenti',
  path: '/allenamenti',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const EntraRoute = EntraRouteImport.update({
  id: '/entra',
  path: '/entra',
  getParentRoute: () => rootRouteImport,
} as any)
const EventiRoute = EventiRouteImport.update({
  id: '/eventi',
  path: '/eventi',
  getParentRoute: () => rootRouteImport,
} as any)
const FornitoriRoute = FornitoriRouteImport.update({
  id: '/fornitori',
  path: '/fornitori',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeguardingRoute = SafeguardingRouteImport.update({
  id: '/safeguarding',
  path: '/safeguarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SocietaRoute = SocietaRouteImport.update({
  id: '/societa',
  path: '/societa',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const AreeIndexRoute = AreeIndexRouteImport.update({
  id: '/aree/',
  path: '/aree/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreeAreaRoute = AreeAreaRouteImport.update({
  id: '/aree/$area',
  path: '/aree/$area',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allenamenti': typeof AllenamentiRoute
  '/calendario': typeof CalendarioRoute
  '/community': typeof CommunityRoute
  '/contatti': typeof ContattiRoute
  '/entra': typeof EntraRoute
  '/eventi': typeof EventiRoute
  '/fornitori': typeof FornitoriRoute
  '/safeguarding': typeof SafeguardingRoute
  '/shop': typeof ShopRoute
  '/societa': typeof SocietaRoute
  '/sponsor': typeof SponsorRoute
  '/aree/$area': typeof AreeAreaRoute
  '/aree/': typeof AreeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allenamenti': typeof AllenamentiRoute
  '/calendario': typeof CalendarioRoute
  '/community': typeof CommunityRoute
  '/contatti': typeof ContattiRoute
  '/entra': typeof EntraRoute
  '/eventi': typeof EventiRoute
  '/fornitori': typeof FornitoriRoute
  '/safeguarding': typeof SafeguardingRoute
  '/shop': typeof ShopRoute
  '/societa': typeof SocietaRoute
  '/sponsor': typeof SponsorRoute
  '/aree/$area': typeof AreeAreaRoute
  '/aree': typeof AreeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allenamenti': typeof AllenamentiRoute
  '/calendario': typeof CalendarioRoute
  '/community': typeof CommunityRoute
  '/contatti': typeof ContattiRoute
  '/entra': typeof EntraRoute
  '/eventi': typeof EventiRoute
  '/fornitori': typeof FornitoriRoute
  '/safeguarding': typeof SafeguardingRoute
  '/shop': typeof ShopRoute
  '/societa': typeof SocietaRoute
  '/sponsor': typeof SponsorRoute
  '/aree/$area': typeof AreeAreaRoute
  '/aree/': typeof AreeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allenamenti'
    | '/calendario'
    | '/community'
    | '/contatti'
    | '/entra'
    | '/eventi'
    | '/fornitori'
    | '/safeguarding'
    | '/shop'
    | '/societa'
    | '/sponsor'
    | '/aree/$area'
    | '/aree/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allenamenti'
    | '/calendario'
    | '/community'
    | '/contatti'
    | '/entra'
    | '/eventi'
    | '/fornitori'
    | '/safeguarding'
    | '/shop'
    | '/societa'
    | '/sponsor'
    | '/aree/$area'
    | '/aree'
  id:
    | '__root__'
    | '/'
    | '/allenamenti'
    | '/calendario'
    | '/community'
    | '/contatti'
    | '/entra'
    | '/eventi'
    | '/fornitori'
    | '/safeguarding'
    | '/shop'
    | '/societa'
    | '/sponsor'
    | '/aree/$area'
    | '/aree/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllenamentiRoute: typeof AllenamentiRoute
  CalendarioRoute: typeof CalendarioRoute
  CommunityRoute: typeof CommunityRoute
  ContattiRoute: typeof ContattiRoute
  EntraRoute: typeof EntraRoute
  EventiRoute: typeof EventiRoute
  FornitoriRoute: typeof FornitoriRoute
  SafeguardingRoute: typeof SafeguardingRoute
  ShopRoute: typeof ShopRoute
  SocietaRoute: typeof SocietaRoute
  SponsorRoute: typeof SponsorRoute
  AreeAreaRoute: typeof AreeAreaRoute
  AreeIndexRoute: typeof AreeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allenamenti': {
      id: '/allenamenti'
      path: '/allenamenti'
      fullPath: '/allenamenti'
      preLoaderRoute: typeof AllenamentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entra': {
      id: '/entra'
      path: '/entra'
      fullPath: '/entra'
      preLoaderRoute: typeof EntraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventi': {
      id: '/eventi'
      path: '/eventi'
      fullPath: '/eventi'
      preLoaderRoute: typeof EventiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornitori': {
      id: '/fornitori'
      path: '/fornitori'
      fullPath: '/fornitori'
      preLoaderRoute: typeof FornitoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safeguarding': {
      id: '/safeguarding'
      path: '/safeguarding'
      fullPath: '/safeguarding'
      preLoaderRoute: typeof SafeguardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/societa': {
      id: '/societa'
      path: '/societa'
      fullPath: '/societa'
      preLoaderRoute: typeof SocietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aree/': {
      id: '/aree/'
      path: '/aree'
      fullPath: '/aree/'
      preLoaderRoute: typeof AreeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aree/$area': {
      id: '/aree/$area'
      path: '/aree/$area'
      fullPath: '/aree/$area'
      preLoaderRoute: typeof AreeAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllenamentiRoute: AllenamentiRoute,
  CalendarioRoute: CalendarioRoute,
  CommunityRoute: CommunityRoute,
  ContattiRoute: ContattiRoute,
  EntraRoute: EntraRoute,
  EventiRoute: EventiRoute,
  FornitoriRoute: FornitoriRoute,
  SafeguardingRoute: SafeguardingRoute,
  ShopRoute: ShopRoute,
  SocietaRoute: SocietaRoute,
  SponsorRoute: SponsorRoute,
  AreeAreaRoute: AreeAreaRoute,
  AreeIndexRoute: AreeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
