import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.0'
const supabase=createClient('https://dfnwzwutvnwiitiffwvr.supabase.co','sb_publishable_n0Fmw2PlLeaXsoFVsKb8MA_VbPqUbNn',{auth:{persistSession:true,autoRefreshToken:true}})
const $=id=>document.getElementById(id),loginView=$('loginView'),appView=$('appView'),blockedView=$('blockedView'),msg=$('loginMsg'),logoutBtn=$('logoutBtn'),userPill=$('userPill')
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const fmt=v=>v?new Intl.DateTimeFormat('it-IT').format(new Date(v+'T12:00:00')):'—'
function showMsg(t,e=false){msg.textContent=t;msg.className='msg'+(e?' error':'')}
async function logout(){await supabase.auth.signOut();location.reload()}
logoutBtn.onclick=logout;$('blockedLogout').onclick=logout
$('loginForm').onsubmit=async e=>{e.preventDefault();const{error}=await supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)return showMsg(error.message,true);await boot()}
$('signupBtn').onclick=async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<8)return showMsg('Inserisci email e una password di almeno 8 caratteri.',true);const{data,error}=await supabase.auth.signUp({email,password});if(error)return showMsg(error.message,true);if(data.session)await boot();else showMsg('Account creato. Controlla la mail di conferma, poi torna qui e accedi.')}
$('refreshBtn').onclick=loadDashboard
async function boot(){const{data:{user}}=await supabase.auth.getUser();if(!user){loginView.classList.remove('hidden');appView.classList.add('hidden');blockedView.classList.add('hidden');return}loginView.classList.add('hidden');logoutBtn.classList.remove('hidden');userPill.classList.remove('hidden');userPill.textContent=user.email||'Utente';const{data:m,error}=await supabase.from('organization_memberships').select('organization_id,role,organizations(name)').eq('user_id',user.id).eq('active',true).limit(1).maybeSingle();if(error||!m){appView.classList.add('hidden');blockedView.classList.remove('hidden');return}blockedView.classList.add('hidden');appView.classList.remove('hidden');$('orgTitle').textContent=m.organizations?.name||'Maglia Assicurazioni';window.orgId=m.organization_id;await loadDashboard()}
async function loadDashboard(){if(!window.orgId)return;$('loading').classList.remove('hidden');$('tableWrap').classList.add('hidden');const{data,error}=await supabase.from('pipeline_cases').select('id,score,reason,stage,assigned_to,metadata,clients(id,last_name,business_name,email,mobile,city,province,lost_at,metadata)').eq('organization_id',window.orgId).eq('pipeline','recovery').not('stage','in','(won,lost,closed)').order('score',{ascending:false}).limit(100);if(error){$('loading').textContent='Errore: '+error.message;return}const rows=(data||[]).sort((a,b)=>Number(a.metadata?.pilot_rank??999)-Number(b.metadata?.pilot_rank??999));$('kRecovery').textContent=rows.length;$('kHigh').textContent=rows.filter(x=>Number(x.score)>=90).length;$('kUnassigned').textContent=rows.filter(x=>!x.assigned_to).length;const{count}=await supabase.from('work_items').select('id',{count:'exact',head:true}).eq('organization_id',window.orgId).not('status','in','(completed,cancelled)');$('kWork').textContent=count??0;$('recoveryBody').innerHTML=rows.map(x=>{const c=x.clients||{},name=c.business_name||c.last_name||'Cliente',rank=x.metadata?.pilot_rank??c.metadata?.recovery_pilot_rank??'—',score=Number(x.score||0),contact=[c.mobile?'<a href="tel:'+esc(c.mobile)+'">'+esc(c.mobile)+'</a>':'',c.email?'<a href="mailto:'+esc(c.email)+'">'+esc(c.email)+'</a>':''].filter(Boolean).join('');return '<tr><td><span class="rank">'+esc(rank)+'</span></td><td><span class="name">'+esc(name)+'</span></td><td>'+esc(c.city||'—')+'</td><td>'+esc(fmt(c.lost_at))+'</td><td>'+esc(x.reason||'Da verificare')+'</td><td><span class="score '+(score>=90?'hi':'')+'">'+score.toFixed(0)+'</span></td><td><div class="contact">'+(contact||'—')+'</div></td><td><span class="stage">'+esc(x.assigned_to?x.stage:'Da assegnare')+'</span></td></tr>'}).join('');$('loading').classList.add('hidden');$('tableWrap').classList.remove('hidden')}
supabase.auth.onAuthStateChange(()=>setTimeout(boot,0));await boot()